CSRF_ENABLED = True
SECRET_KEY = 'you-will-never-guess'
PUBLIC_KEY = 'XXXXXXX'
PRIVATE_KEY = 'XXXXXXX'
ASSOCIATE_TAG = 'XXXXXXX'
WDC_TA_USER_NAME = 'XXXXXXX'
WDC_TA_PASSWORD = 'XXXXXXX'
WDC_TA_VERSION = 'XXXXXXX'